### ISSUE TITLE
Ordering the blog content in the content section based on user desired order

### ISSUE THREAD

**Issue by taragurung** [HYP3R00T/CelestialDocs#1]
**Is your feature request related to a problem? Please describe.**
The ordering of the content section is based on alphabets, which might not be suitable for everyone. 
**Describe the solution you'd like**
I would like to have content ordering that can be set by users like : order:1, 2,3 on each content to set the orders while listing of the content

**Describe alternatives you've considered**

**Additional context**

**Comment by HYP3R00T** [comment]
Thanks for raising the concern. 

I just want to reiterate what I understood. We have top-level folders and files that can be modified [(read more about it here)](https://celestialdocs.hyperoot.dev/guides/sidebar-navigation/#custom-order). You want the option to provide custom orders to the subitems as well. 

I am working on that feature. For the time being, there is a workaround. Name your files with numbers like `01-file1.md` and `02-actual-file.md`. This way we can provide custom orders to inner files and folders.

**Comment by HYP3R00T** [comment]
Hi @taragurung 

I have added the feature for custom order of inner items. Kindly check out the documentation to learn more about its implementation. 
https://celestialdocs.hyperoot.dev/guides/sidebar-navigation/#custom-order

**Comment by taragurung** [comment]
Thanks! for the quick response. 
For inner content its working fine with the work-around of renaming file as 01,02
![ordering](https://github.com/user-attachments/assets/45c996dd-7b64-4682-98be-37c04a2ef694)

**but for the main title how to achieve it**
Like in here Basic Command should be after Docker but due to alphabets its getting on top. If we use workaround here, I will get 01 02 in the url so dont want to do that

**Comment by HYP3R00T** [comment]
You can order them as well. I have documented the same [here](http://localhost:4321/guides/sidebar-navigation#custom-order). 

If you go to the `config.ts` file in the root directory, you can place an order for all the pages. For instance,

```
export const side_nav_menu_order: string[] = [
  "getting-started",
  "guides",
  "guides/pages",
  "guides/table-of-contents",
  "guides/sidebar-navigation",
  "custom-components",
  "reference",
];
```

This is the order I have for the official documentation site. `getting-started` is a `mdx` file whereas others are folders. If you notice, I have mentioned the order for nested pages as well (`guides/pages`, `guides/table-of-contents` and `guides/sidebar-navigation` for instance).

![image](https://github.com/user-attachments/assets/bf4cfc75-cedd-4f4b-a01c-86936c56ce0c)

**Comment by HYP3R00T** [comment]
@taragurung 
If you have hosted your code somewhere, then share your repo link. I can take a look and help you with your query.
