### ISSUE TITLE
Sidebar Intentation depending on subfolders

### ISSUE THREAD

**Issue by gmichaelides** [HYP3R00T/CelestialDocs#4]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Indent the sidebar structure according to document folder structure

**Describe alternatives you've considered**

**Additional context**
Sample screenshot
![image](https://github.com/user-attachments/assets/285ca8ec-a21e-4f32-93ac-bf9dde58c927)

**Comment by HYP3R00T** [comment]
Level one folders are in bold and all other nested files are in normal font width. You can modify the code at `src/components/docs/SideNavMenu.astro` to your choice. Ideally we don't have indentation in sidenav for documentation site as it's a waste of space. 

As per my original decision regarding the design of the page, I won't be making this changes.
